paths:
  settings: "C:\Users\SamLyndon\AppData\Roaming\Code\User\globalStorage\rooveterinaryinc.roo-cline\settings\cline_mcp_settings.json"
  markdown: "C:\Users\SamLyndon\Desktop\cline_mcp_settings.md"
watcher:
  pollInterval: 1000
  awaitWriteFinish:
    stabilityThreshold: 2000
    pollInterval: 500
service:
  autoStart: true
  port: 8080
  logLevel: info
  logFile: ""
notifications:
  enabled: true
  onSuccess: true
  onError: true
