paths:
  settings: /Users/samlyndon/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json
  markdown: /Users/samlyndon/repos/custom/mcp_servers_and_tools_1.md
watcher:
  pollInterval: 1000
  awaitWriteFinish:
    stabilityThreshold: 2000
    pollInterval: 500
service:
  autoStart: true
  port: 8080
  logLevel: info
  logFile: ""
notifications:
  enabled: true
  onSuccess: true
  onError: true
